# Generated by Django 5.0.3 on 2024-11-17 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelfield',
            name='related_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='generatedapp',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('ForeignKey', 'ForeignKey')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='max_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
