# Generated by Django 5.0.3 on 2024-11-17 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apphub', '0002_modelfield_related_model_alter_generatedapp_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelfield',
            name='related_model',
        ),
        migrations.AlterField(
            model_name='generatedapp',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='field_type',
            field=models.CharField(choices=[('CharField', 'CharField'), ('IntegerField', 'IntegerField'), ('BooleanField', 'BooleanField'), ('DateField', 'DateField')], max_length=50),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='modelfield',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
